name: Verify

on:
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  verify:
    name: Reusable verify workflow
    uses: reside-eng/workflow-templates-library/.github/workflows/verify_library.yml@add-CI-analytics
    with:
      NODE_VERSION: 20.x
      SLACK_NOTIFICATION_SECRET: SLACK_WEBHOOK_PLATFORM_NONPROD
      ENABLE_TYPES_CHECK: true
    secrets: inherit
