name: Verify

on: [pull_request]

jobs:
  verify:
    name: Reusable verify workflow
    uses: reside-eng/workflow-templates-library/.github/workflows/verify_library.yml@v1
    with:
      NODE_VERSION: 18.x
      PACKAGE_MANAGER: yarn-berry
      SLACK_NOTIFICATION_SECRET: SLACK_WEBHOOK_PLATFORM_PROD
      ENABLE_TYPES_CHECK: true
    secrets: inherit
