name: Verify

on: [pull_request]

env:
  NODE_VERSION: 16.x

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.5

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Configure package manager
        run: |
          echo Configuring NPM_READ_TOKEN globally for .npmrc
          npm config set '//registry.npmjs.org/:_authToken' ${{ env.NPM_TOKEN }}
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_READ_TOKEN }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Check types
        run: yarn types

      # TODO: [PLAT-1074] Provide inversion of control for app teams to manage particular CI steps within package.json scripts
      - name: Test
        run: yarn test:cov

      - name: Comment test coverage
        uses: raulanatol/jest-coverage-comment-action@v1.1.2
        with:
          use-existing-reports: true

      - name: Build package
        run: yarn build

      - name: Archive workspace on failure
        if: failure()
        run: zip -r workspace-files ./

      - uses: actions/upload-artifact@v2.2.4
        if: failure()
        with:
          name: workspace
          path: workspace-files.zip

  notification:
    if: always() && github.actor != 'dependabot[bot]'
    name: notification
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.4.0

      - uses: technote-space/workflow-conclusion-action@v2.2.1

      - uses: reside-eng/workflow-status-notification-action@v1.0.0
        with:
          current-status: ${{ env.WORKFLOW_CONCLUSION }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_PLATFORM_PROD }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
